volumes:
  files:
  mysql:
  redis:

networks:
  owncloud_net:

services:
  owncloud:
    image: ${DOCKER_USER}/owncloud:latest
    container_name: owncloud_server
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      OWNCLOUD_DOMAIN: ${OWNCLOUD_DOMAIN}
      OWNCLOUD_TRUSTED_DOMAINS: ${OWNCLOUD_TRUSTED_DOMAINS}
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: ${OWNCLOUD_DB_NAME}
      OWNCLOUD_DB_USERNAME: ${OWNCLOUD_DB_USERNAME}
      OWNCLOUD_DB_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
      OWNCLOUD_DB_HOST: mariadb
      OWNCLOUD_ADMIN_USERNAME: ${ADMIN_USERNAME}
      OWNCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data
    networks:
      - owncloud_net

  mariadb:
    image: mariadb:10.11
    container_name: owncloud_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${OWNCLOUD_DB_USERNAME}
      MYSQL_PASSWORD: ${OWNCLOUD_DB_PASSWORD}
      MYSQL_DATABASE: ${OWNCLOUD_DB_NAME}
      MARIADB_AUTO_UPGRADE: 1
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - owncloud_net

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: unless-stopped
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
    networks:
      - owncloud_net
